apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-service-2
spec:
  replicas: 2
  selector:
    matchLabels:
      service: service-2
  template:
    metadata:
      name: pod-service-2
      labels:
        service: service-2
    spec:
      containers:
      - name: node
        image: hinora/service-2
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
        ports:
          - containerPort: 3002