apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-service-1
spec:
  replicas: 2
  selector:
    matchLabels:
      service: service-1
  template:
    metadata:
      name: pod-service-1
      labels:
        service: service-1
    spec:
      containers:
      - name: node
        image: hinora/service-1
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
        ports:
          - containerPort: 3001